springdoc:
  packages-to-scan: io.github.bbortt.snow.white.microservices.report.coordinator.api.api.rest.resource
spring:
  jpa:
    open-in-view: false
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: 'io.github.bbortt.snow.white.*'
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  profiles:
    default: prod
