apiVersion: v2
name: snow-white
description: A Helm chart for deploying snow-white
type: application
version: 0.1.0
appVersion: v1.0.0-ci.0
maintainers:
  - name: Timon Borter
    email: timon.borter@gmx.ch
dependencies:
  - name: kafka
    version: 32.4.3
    repository: 'https://charts.bitnami.com/bitnami'
    condition: kafka.enabled
  - name: influxdb
    version: 7.1.20
    repository: 'https://charts.bitnami.com/bitnami'
    condition: influxdb.enabled
  - name: postgresql
    version: 18.1.13
    repository: 'https://charts.bitnami.com/bitnami'
    condition: postgresql.enabled
  - name: redis
    version: 23.2.12
    repository: 'https://charts.bitnami.com/bitnami'
    condition: redis.enabled
