apiVersion: v2
name: snow-white
description: A Helm chart for deploying snow-white
type: application
version: 0.1.0
appVersion: v1.0.0-ci.0
maintainers:
  - name: Timon Borter
    email: timon.borter@gmx.ch
dependencies:
  - name: influxdb
    version: 4.12.5
    repository: 'https://helm.influxdata.com/'
    condition: influxdb.enabled
  - name: postgresql
    version: 18.1.15
    repository: 'https://charts.bitnami.com/bitnami'
    condition: postgresql.enabled
  - name: redis
    version: 24.1.0
    repository: 'https://charts.bitnami.com/bitnami'
    condition: redis.enabled
engine: gotpl
