influxdb:
  url: http://localhost:8086
  org: snow-white
  bucket: raw-data
snow:
  white:
    openapi:
      coverage:
        stream:
          api-index:
            base-url: http://localhost:8085
          calculation-request-topic: snow-white-calculation-request
          init-topics: true
          openapi-calculation-response-topic: snow-white-openapi-calculation-response
spring:
  devtools:
    livereload:
      enabled: true
