snow:
  white:
    api:
      sync:
        job:
          api-index:
            base-url: http://localhost:8085
          artifactory:
            base-url: http://localhost:3000/artifactory
            repository: snow-white-generic-local
spring:
  devtools:
    livereload:
      enabled: true
