snow:
  white:
    api:
      sync:
        job:
          api-index:
            base-url: http://localhost:8085
          artifactory:
            base-url: http://localhost:3000
            repository: snow-white-generic-local
            custom-api-name-json-path: info.extensions.x-api-name
spring:
  devtools:
    livereload:
      enabled: true
