snow:
  white:
    api:
      sync:
        job:
          api-index:
            base-url: http://localhost:8085
          service-interface:
            index-uri: /localhost.json
            base-url: http://localhost:3000
spring:
  devtools:
    livereload:
      enabled: true
