management:
  server:
    port: 8090
springdoc:
  swagger-ui:
    urls:
      - name: quality-gate-api
        display-name: Quality-Gate API
        url: '${snow.white.api.gateway.public-url}/v3/api-docs/quality-gate-api'
      - name: report-coordinator-api
        display-name: Report Coordinator API
        url: '${snow.white.api.gateway.public-url}/v3/api-docs/report-coordinator-api'
