springdoc:
  packages-to-scan: io.github.bbortt.snow.white.microservices.quality.gate.api.api.rest
spring:
  flyway:
    placeholders:
      app_user: ${spring.datasource.username}
      app_schema: ${spring.flyway.schemas:public}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  profiles:
    default: prod
